In [7]:
import numpy as np

# Scalar
scalar = 5
print("Scalar:", scalar)

# Vector (1D array)
vector = np.array([2, 4, 6])
print("Vector:", vector)

# Matrix (2D array)
matrix = np.array([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

# Tensor (3D array)
tensor = np.random.rand(2, 3, 4)  # 2 matrices of 3x4
print("Tensor shape:", tensor.shape)
print("Tensor: \n", tensor)

Scalar: 5
Vector: [2 4 6]
Matrix:
 [[1 2]
 [3 4]]
Tensor shape: (2, 3, 4)
Tensor: 
 [[[0.34097589 0.57275201 0.30107296 0.36832019]
  [0.99286424 0.80101732 0.91872893 0.31033868]
  [0.93714958 0.02449156 0.89191822 0.25784927]]

 [[0.50563352 0.34252575 0.6398907  0.04995871]
  [0.81573086 0.19501888 0.63499339 0.24150427]
  [0.96082836 0.1032149  0.46315035 0.68179747]]]


In [6]:
I = np.eye(3)
print("Identity Matrix:\n", I)

# Inverse
M = np.array([[4, 7], [2, 6]])
inv_M = np.linalg.inv(M)
print("Inverse Matrix:\n", inv_M)

# M * M⁻¹ should be the identity
print("Product (M * inv_M):\n", np.dot(M, inv_M))

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Inverse Matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Product (M * inv_M):
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
