In [1]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])

print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)
print("Division:\n", a / b)


Addition:
 [[11 22]
 [33 44]]
Subtraction:
 [[ -9 -18]
 [-27 -36]]
Multiplication:
 [[ 10  40]
 [ 90 160]]
Division:
 [[0.1 0.1]
 [0.1 0.1]]


In [4]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])  # shape (2,)

print("Broadcasted Addition:\n", a + b)

#NumPy automatically “stretches” shapes where possible.
#Here, b is broadcast to match a's shape:

Broadcasted Addition:
 [[11 22]
 [13 24]]


In [5]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])

print("Matrix Multiplication:\n", a @ b)


Matrix Multiplication:
 [[ 4  4]
 [10  8]]


In [8]:
a = np.array([[1, 2], [3, 4], [5, 6]])  # shape (3, 2)
reshaped = a.reshape((2, 3))           # shape (2, 3)
print("Reshaped:\n", reshaped)


Reshaped:
 [[1 2 3]
 [4 5 6]]


In [9]:
#summing along axes
a = np.array([[1, 2], [3, 4]])

print("Sum all:", np.sum(a))
print("Sum along axis 0 (column-wise):", np.sum(a, axis=0))
print("Sum along axis 1 (row-wise):", np.sum(a, axis=1))

Sum all: 10
Sum along axis 0 (column-wise): [4 6]
Sum along axis 1 (row-wise): [3 7]


In [10]:
#Transpose of tensor
a = np.array([[1, 2], [3, 4]])
print("Transposed:\n", a.T)


Transposed:
 [[1 3]
 [2 4]]


In [14]:
#3D tensor summing along axes
tensor = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

print("Original tensor shape:", tensor.shape)
print("Tensor:\n", tensor)

sum_axis_0 = np.sum(tensor, axis=0)
print("\nSum along axis 0 (blocks): shape", sum_axis_0.shape)
print(sum_axis_0)

sum_axis_1 = np.sum(tensor, axis=1)
print("\nSum along axis 1 (rows): shape", sum_axis_1.shape)
print(sum_axis_1)

sum_axis_2 = np.sum(tensor, axis=2)
print("\nSum along axis 2 (columns): shape", sum_axis_2.shape)
print(sum_axis_2)


Original tensor shape: (2, 3, 4)
Tensor:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Sum along axis 0 (blocks): shape (3, 4)
[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]

Sum along axis 1 (rows): shape (2, 4)
[[15 18 21 24]
 [51 54 57 60]]

Sum along axis 2 (columns): shape (2, 3)
[[10 26 42]
 [58 74 90]]
