In [3]:
import numpy as np

In [5]:
v=np.array([2,4,5]) #1D array
print(v)

m=np.array([[1,2,3],[4,5,6]]) #2D array or matrix
print(m)



[2 4 5]
[[1 2 3]
 [4 5 6]]


In [7]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

# Addition of two 2-D matrix
print(a+b)
# Subtraction of two 2-D matrix
print(a-b)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [9]:
# Scalar multiplication
print(2*a)

[[2 4]
 [6 8]]


In [12]:
# Transpose of matrix
print("Original: \n", a)
print("Transpose: \n", a.T)

Original: 
 [[1 2]
 [3 4]]
Transpose: 
 [[1 3]
 [2 4]]


In [13]:
# dot product - it is for vectors i.e. 1-D array
c=np.array([1,2])
d=np.array([3,4])
dotproduct = np.dot(c,d) #1*3 + 2*4
print(dotproduct)


11


In [14]:
# matrix multiplication
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [16]:
# matrix multiplication
e=np.array([[4,5],[9,5]])
f=np.array([[6,6],[2,2]])

print(np.dot(e, f))

[[34 34]
 [64 64]]


In [19]:
# probability

p_heads=0.2
p_tails=1-p_heads
print(p_heads, p_tails)

0.2 0.8


In [15]:
# Challenge
#   Create a 2x2 matrix
#   Multiply it with another 2x2 matrix
#   Find its transpose
#   Calculate dot product of two 1D arrays
#   Print the mean and standard deviation of a vector

f = np.array([[1,2],[3,4]])
g = np.array([[7,8],[9,10]])
mul = np.dot(f,g)
print(f"Multiplication of two 2D arrays f and g is: \n{mul}")
print(f"Transpose of f is: \n{f.T}")
print(f"Transpose of g is: \n{g.T}")
 
h = np.array([1,2,3])
i = np.array([4,5,6])
dp = np.dot(h,i);
print(f"Dot product of h and i is: {dp}")

meanf = np.mean(h)
print(f"Mean of f is: {meanf}")

std = np.std(g)
print(f"Standard deviation of g is: {std}")

Multiplication of two 2D arrays f and g is: 
[[25 28]
 [57 64]]
Transpose of f is: 
[[1 3]
 [2 4]]
Transpose of g is: 
[[ 7  9]
 [ 8 10]]
Dot product of h and i is: 32
Mean of f is: 2.0
Standard deviation of g is: 1.118033988749895
